### PR TITLE
Some more RTL updates

### PR DESCRIPTION
**Pull request by nadavkav**
Code comments indicate the pages that are affected by proposed change.
(We are getting very close to the end :-)

### CODE REVIEW

**Comment by nadavkav** [comment]
Hi @bmbrands , How about integrating this?

**Comment by nadavkav** [comment]
Hi @bmbrands , How about integrating this? (for M31)

**Comment by nadavkav** [comment]
Hi @bmbrands , How about integrating this? (for M31)

**Comment by bmbrands** [comment]
Hi Nadav,

Sorry missed this one! thanks for reminding me

**Comment by nadavkav** [comment]
Bless you :-)

**Pull request merged**
